import Link from "next/link";
import ShaderCanvas from "./components/ShaderCanvas";
import { Reveal, SectionLabel } from "./components/UI";
import { skills } from "./data";
import ScrollProjects from "./components/ScrollProjects";

export default function Home(){return <>
  <section className="hero grid-bg"><ShaderCanvas className="hero-shader"/><div className="cmd-backdrop" aria-hidden="true"><div className="cmd-bar"><span/><span/><span/><b>stone@portfolio — system console</b></div><div className="cmd-lines"><p><i>&gt;</i> initializing portfolio...</p><p><i>&gt;</i> loading frontend ........ <strong>OK</strong></p><p><i>&gt;</i> loading backend ......... <strong>OK</strong></p><p><i>&gt;</i> connecting RAG .......... <strong>OK</strong></p><p><i>&gt;</i> agent runtime ........... <strong>READY</strong></p><p className="cmd-welcome"><i>&gt;</i> welcome, visitor<span className="cmd-cursor"/></p></div></div><div className="hero-content"><Reveal><p className="eyebrow">FULL-STACK DEVELOPER · AI APPLICATION ENGINEER</p><h1><span className="metallic-text">Building modern web<br/>products and</span><br/><em className="aurora-text">intelligent systems.</em></h1><p className="hero-lede">I build polished web experiences and intelligent applications—from responsive frontends and scalable backends to RAG systems and AI agents.</p><div className="actions"><Link className="button primary" href="/projects">View Projects <span>→</span></Link><Link className="button ghost" href="/contact">Contact Me</Link></div><p className="terminal">stone@portfolio:~$ Vancouver, Canada<span className="cursor"/></p></Reveal></div><div className="hero-footnote">SCROLL TO EXPLORE <span>↓</span></div></section>
  <section className="section"><div className="section-head"><div><SectionLabel>01_CAPABILITIES</SectionLabel><h2>Capabilities</h2></div><span className="system-status">SYSTEMS ONLINE</span></div><div className="skill-grid">{skills.map(s=><Reveal className="skill-card corner" key={s.title}><div className="skill-icon">{s.index}</div><h3>{s.title}</h3><p>{s.items.slice(0,4).join(" · ")}</p><span className="status-dot">● ACTIVE</span></Reveal>)}</div></section>
  <section className="section projects-home"><div className="section-head"><div><SectionLabel>02_SELECTED_WORK</SectionLabel><h2>Featured Projects</h2></div><Link className="text-link" href="/projects">VIEW ALL PROJECTS →</Link></div><ScrollProjects/></section>
  <section className="intro section"><SectionLabel>03_PROFILE</SectionLabel><Reveal><p className="big-copy">I&apos;m Stone, a developer based in Vancouver. I work across <em>frontend, backend, and applied AI</em> to turn ideas into useful, well-crafted products.</p><Link className="text-link" href="/about">MORE ABOUT ME →</Link></Reveal></section>
  <section className="closing grid-bg"><Reveal><h2><span className="metallic-text">Have an idea</span><br/><em className="aurora-text">worth building?</em></h2><p>Let&apos;s turn it into a useful, well-crafted product.</p><Link className="button primary" href="/contact">Contact Me <span>→</span></Link></Reveal></section>
  </>}
