import Link from "next/link";
import ShaderCanvas from "./components/ShaderCanvas";
import { ProjectCard, Reveal, SectionLabel } from "./components/UI";
import { projects, skills } from "./data";

export default function Home(){return <>
  <section className="hero grid-bg"><ShaderCanvas className="hero-shader"/><div className="cmd-backdrop" aria-hidden="true"><div className="cmd-bar"><span/><span/><span/><b>stone@portfolio — system console</b></div><div className="cmd-lines"><p><i>stone@portfolio:~$</i> initialize profile</p><p><i>[ OK ]</i> frontend.modules ........ loaded</p><p><i>[ OK ]</i> backend.services ....... loaded</p><p><i>[ OK ]</i> rag.pipeline ............ ready</p><p><i>[ OK ]</i> agent.runtime ........... ready</p><p><i>stone@portfolio:~$</i> deploy useful_systems --mode production</p><p className="cmd-dim">compiling ideas into reliable products...</p><p><i>STATUS</i> ALL SYSTEMS OPERATIONAL <span className="cmd-cursor"/></p></div></div><div className="hero-content"><Reveal><p className="eyebrow">VANCOUVER, CANADA · FULL-STACK + AI</p><h1>Full-Stack Developer<br/>&amp; <em>AI Application<br/>Engineer</em></h1><p className="hero-lede">I build polished web experiences and intelligent applications—from responsive frontends and scalable backends to RAG systems and AI agents.</p><div className="actions"><Link className="button primary" href="/projects">View Projects <span>→</span></Link><Link className="button ghost" href="/contact">Contact Me</Link></div><p className="terminal">stone@portfolio:~$ building useful systems<span className="cursor"/></p></Reveal></div><div className="hero-footnote">SCROLL TO EXPLORE <span>↓</span></div></section>
  <section className="section"><div className="section-head"><div><SectionLabel>01_CAPABILITIES</SectionLabel><h2>Capabilities</h2></div><span className="system-status">SYSTEMS ONLINE</span></div><div className="skill-grid">{skills.map(s=><Reveal className="skill-card corner" key={s.title}><div className="skill-icon">{s.index}</div><h3>{s.title}</h3><p>{s.items.slice(0,4).join(" · ")}</p><span className="status-dot">● ACTIVE</span></Reveal>)}</div></section>
  <section className="section projects-home"><div className="section-head"><div><SectionLabel>02_SELECTED_WORK</SectionLabel><h2>Featured Projects</h2></div><Link className="text-link" href="/projects">VIEW ALL PROJECTS →</Link></div><div className="featured-grid">{projects.map(p=><Reveal key={p.slug}><ProjectCard project={p}/></Reveal>)}<div className="coming corner"><span>03</span><div><p>SYSTEM INITIALIZING...</p><h3>PROJECT 03</h3><small>New project in development.</small></div></div></div></section>
  <section className="intro section"><SectionLabel>03_PROFILE</SectionLabel><Reveal><p className="big-copy">I&apos;m Stone, a developer based in Vancouver. I work across <em>frontend, backend, and applied AI</em> to turn ideas into useful, well-crafted products.</p><Link className="text-link" href="/about">MORE ABOUT ME →</Link></Reveal></section>
  <section className="closing grid-bg"><Reveal><h2>Have a product,<br/>problem, or idea worth<br/>building?</h2><Link className="button primary" href="/contact">Contact Me <span>→</span></Link></Reveal></section>
  </>}
